config/routes.rb
Rails.application.routes.draw do
  resources :profiles

  resources :games
  match "start", :to => "games#start", via: [:get, :post]
  root to: 'games#start'
  devise_for :users
  resources :users
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  has_attached_file :flash
  do_not_validate_attachment_file_type :image
  do_not_validate_attachment_file_type :flash

end

app/models/profile.rb
class Profile < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  respond_to :html, :json, :js
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  respond_to :html, :json, :js
  before_action :set_game, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, :only => [:destroy, :update, :index, :new, :create]
  def index
    @games = Game.all
    if Profile.first
      @profile = Profile.first
    else
      @profile = Profile.create(:flash_size => 600, :flash_width=>400 )
    end
    respond_with(@games)
  end

  def start
    @games = Game.all
    respond_with(@games)
  end

  def show
    @height = Profile.first.flash_size rescue 400
    @width = Profile.first.flash_width rescue 600
    respond_with(@game)
  end

  def new
    @game = Game.new
    respond_with(@game)
  end

  def edit
  end

  def create
    @game = Game.new(game_params)
    flash[:notice] = 'Game was successfully created.' if @game.save
    respond_with(@game)
  end

  def update
    flash[:notice] = 'Game was successfully updated.' if @game.update(game_params)
    respond_with(@game)
  end

  def destroy
    @game.destroy
    respond_with(@game)
  end

  private
    def set_game
      @game = Game.find(params[:id])
    end

    def game_params
      params.require(:game).permit(:title, :description, :active, :image, :flash)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  def index
    @profiles = Profile.all
    respond_with(@profiles)
  end

  def show
    respond_with(@profile)
  end

  def new
    @profile = Profile.new
    respond_with(@profile)
  end

  def edit
  end

  def create
    @profile = Profile.new(profile_params)
    flash[:notice] = 'Profile was successfully created.' if @profile.save
    respond_with(@profile)
  end

  def update
    flash[:notice] = 'Profile was successfully updated.' if @profile.update(profile_params)
    respond_with(@profile)
  end

  def destroy
    @profile.destroy
    respond_with(@profile)
  end

  private
    def set_profile
      @profile = Profile.find(params[:id])
    end

    def profile_params
      params.require(:profile).permit(:flash_size, :flash_width, :active)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/_form.html.slim
= simple_form_for @game, :html => { :class => "form-horizontal" } do |f|
  = f.input :title
  = f.input :description
  = f.input :active
  = f.input :image, as: :file
  = f.input :flash, as: :file
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    '
    = link_to t('.cancel', :default => t("helpers.links.cancel")), games_path, :class => 'btn'

app/views/games/edit.html.slim
- model_class = Game
div class="page-header"
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/games/index.html.slim
- model_class = Game
div class="page-header"
  h1=t '.title', :default => 'Список Игор'
.well
  = render :partial => "/profiles/form"
  

table class="table table-striped"
  thead
    tr
      th= model_class.human_attribute_name(:id)
      th= model_class.human_attribute_name(:title)
      th= model_class.human_attribute_name(:description)
      th= model_class.human_attribute_name(:active)
      th= model_class.human_attribute_name(:created_at)
      th=t '.actions', :default => t("helpers.actions")
  tbody
    - @games.each do |game|
      tr
        td= link_to game.id, game_path(game)
        td= game.title
        td= game.description
        td= game.active
        td=l game.created_at
        td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_game_path(game), :class => 'btn btn-mini'
          '
          = link_to t('.destroy', :default => t("helpers.links.destroy")), game_path(game), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_game_path, :class => 'btn btn-primary'

app/views/games/new.html.slim
- model_class = Game
div class="page-header"
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/games/show.html.slim
= button_to '<< К списку игор', start_path, :class=>'btn btn-primary'
/=binding.pry
div align="center" 
  object height="#{@height}" width="#{@width}" 
    param name="movie" value=""
      param name="quality" value="high" 
        embed height="#{@height}" width="#{@width}" pluginspage="http://www.macromedia.com/go/getflashplayer" quality="high" src='#{@game.flash.url}' type="application/x-shockwave-flash" 
hr
/= link_to '<< К списку игор', start_path, :class=>'btn btn-primary'
        

app/views/games/start.html.slim
- @games.each_slice(4) do |slice|
  hr
  .row-fluid
    - slice.each do |game|
      .span3
        div.alert.alert-success.page-header
          h3 
            strong = game.title 
        div.well style='' align="center"
          hr
          a href="/games/#{game.id}" 
            = image_tag("#{game.image.url}", :class=>"img-polaroid")
          hr
          = button_to 'Играть', "/games/#{game.id}",method: :get,  :class=> 'btn btn-primary'
          /div.thumbnail
            /.well
            /= link_to image_tag("#{game.image.url}"), {:action => 'show', :controller => 'games', :id=>game}              
            /p 
              = game.description

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 2.3
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? "success" : "error"}" 
    a.close[data-dismiss="alert"]
      | ×
    = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 2.3
.navbar.navbar-inverse.navbar-fixed-top
  .navbar-inner
    .container
      a.btn.btn-navbar data-target=".nav-collapse" data-toggle="collapse" 
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a.brand href="/"  Kidlandia
      .container.nav-collapse
        ul.nav
          li.divider-vertical
            a href="/" 
              i.icon-file 
              |  Выбрать игру
          - if user_signed_in?
            li.divider-vertical
              a href="/games" 
                i.icon-question-sign
                |  Игры
            li.divider-vertical
              a href=(edit_user_registration_path(:method => :get)) 
                i.icon-user
                =  current_user.email
            li.divider-vertical
              a data-method="delete" href=destroy_user_session_path 
                i.icon-off
                |  Выход

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
<% end %>

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Kidsgame'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Kidsgame'}"
    == stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => true
    == javascript_include_tag 'application', 'data-turbolinks-track' => true
    == csrf_meta_tags
  body style="padding-top: 60px;"
    / application layout styled for Bootstrap 2.3
    header
      == render 'layouts/navigation'
    main[role="main"]
      .container
        .content
          .row
            .span12
              == render 'layouts/messages'
              == yield
          footer

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
<div align="center"><object width="640" height="480"><param name="movie" value="http://www.embedflashgames.org/games/super-bike-ride.swf"><param name="quality" value="high"><embed src="http://www.embedflashgames.org/games/super-bike-ride.swf" quality="high" width="640" height="400" type="application/x-shockwave-flash" pluginspage= "http://www.macromedia.com/go/getflashplayer"></embed></object><br/><a href="http://www.knugo.com"><strong>knugo.com</strong></a></div>
<p>

This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/profiles/_form.html.slim
= simple_form_for @profile, :remote => true, :html => { :class => "form-horizontal" } do |f|
  = f.input :flash_size, label: 'Высота окна'
  = f.input :flash_width, label: 'Ширина окна'
  = f.input :active
  .form-actions
    = f.button :submit, 'Сохранить настройки',:class => 'btn-primary'
    '
    = link_to t('.cancel', :default => t("helpers.links.cancel")), profiles_path, :class => 'btn'

app/views/profiles/edit.html.slim
- model_class = Profile
div class="page-header"
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/profiles/index.html.slim
- model_class = Profile
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
table class="table table-striped"
  thead
    tr
      th= model_class.human_attribute_name(:id)
      th= model_class.human_attribute_name(:flash_size)
      th= model_class.human_attribute_name(:active)
      th= model_class.human_attribute_name(:created_at)
      th=t '.actions', :default => t("helpers.actions")
  tbody
    - @profiles.each do |profile|
      tr
        td= link_to profile.id, profile_path(profile)
        td= profile.flash_size
        td= profile.active
        td=l profile.created_at
        td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_profile_path(profile), :class => 'btn btn-mini'
          '
          = link_to t('.destroy', :default => t("helpers.links.destroy")), profile_path(profile), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_profile_path, :class => 'btn btn-primary'

app/views/profiles/new.html.slim
- model_class = Profile
div class="page-header"
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/profiles/show.html.slim
- model_class = Profile
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human.titleize

p
  strong= model_class.human_attribute_name(:flash_size) + ':'
  br
  = @profile.flash_size
p
  strong= model_class.human_attribute_name(:active) + ':'
  br
  = @profile.active

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), profiles_path, :class => 'btn'
  '
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_profile_path(@profile), :class => 'btn'
  '
  = link_to t('.destroy', :default => t("helpers.links.destroy")), profile_path(@profile), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<h3>Welcome</h3>

<p>
<div align="center"><object width="640" height="480">
    <param name="movie" value="<%= asset_path('super-bike-ride.swf') %>">
    <param name="quality" value="high">
    <embed src="<%= asset_path('super-bike-ride.swf') %>" quality="high" width="640" height="400" type="application/x-shockwave-flash" pluginspage= "http://www.macromedia.com/go/getflashplayer">
    </embed>
</object><br/><a href="http://www.knugo.com"><strong>knugo.com</strong></a></div>
<p>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>